update archive component, no works with slimscroll
{
  "name": "project",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run multikart-backend:serve-ssr",
    "serve:ssr": "node dist/server/main.js",
    "build:ssr": "ng build --prod && ng run multikart-backend:server:production",
    "prerender": "ng run multikart-backend:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.0.0",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/forms": "~9.0.0",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/platform-server": "~9.0.0",
    "@angular/router": "~9.0.0",
    "@ks89/angular-modal-gallery": "^7.2.5",
    "@ng-bootstrap/ng-bootstrap": "^5.2.1",
    "@nguniversal/express-engine": "^9.0.0",
    "@swimlane/ngx-charts": "^13.0.2",
    "@swimlane/ngx-datatable": "^16.0.3",
    "angular-count-to": "0.0.3",
    "bootstrap": "^4.4.1",
    "chart.js": "^2.9.3",
    "chartist": "^0.11.4",
    "classlist.js": "^1.1.20150312",
    "express": "^4.15.2",
    "feather-icons": "^4.26.0",
    "flag-icons": "^2.0.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "mousetrap": "^1.6.5",
    "ng-animate": "^0.3.4",
    "ng-chartist": "^4.1.0",
    "ng2-charts": "^2.3.0",
    "ng2-completer": "^3.0.3",
    "ng2-datepicker": "^3.1.1",
    "ng2-google-charts": "^5.0.0",
    "ng2-smart-table": "^1.5.0",
    "ngx-ckeditor": "^8.0.0",
    "ngx-dropzone-wrapper": "^8.0.0",
    "ngx-owl-carousel-o": "^2.0.3",
    "ngx-slimscroll": "^8.1.0",
    "rxjs": "~6.5.4",
    "screenfull": "^5.0.1",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.1",
    "@angular/cli": "~9.0.1",
    "@angular/compiler-cli": "~9.0.0",
    "@angular/language-service": "~9.0.0",
    "@nguniversal/builders": "^9.0.0",
    "@types/chart.js": "^2.9.13",
    "@types/express": "^4.17.0",
    "@types/hammerjs": "^2.0.36",
    "@types/jasmine": "^3.5.3",
    "@types/jasminewd2": "~2.0.8",
    "@types/mousetrap": "^1.6.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "~3.1.0",
    "karma-jasmine-html-reporter": "^1.5.2",
    "protractor": "~5.4.3",
    "ts-loader": "^6.2.1",
    "ts-node": "~8.6.2",
    "tslint": "~6.0.0",
    "typescript": "^3.7.5",
    "webpack-cli": "^3.3.10"
  }
}
error:
when compile ,I got this error
I tried to fix it by downloading a version, but surely as the slimscroll version change was broken, the change was done locally, below I leave you the error.

ERROR in node_modules/ng2-datepicker/node_modules/ngx-slimscroll/dist/app/ngx-slimscroll/classes/slimscroll-options.class.d.ts:1:10 - error TS2440: Import declaration conflicts with local declaration of 'ISlimScrollOptions'.

1 import { ISlimScrollOptions } from './slimscroll-options.class';