Issue with Angular version breaks builds and npm start.
When trying to run npm start, I'm getting the following error:
Angular compiler v5.2.0 getOutputName is not a function.
Details: https://github.com/angular/angular/issues/21621

This issue is resolved on 5.2.3 as explained on
https://github.com/angular/angular/issues/21621#issuecomment-363763368